index:
    path: /
    controller: App\Controller\HomeController::index
bien:
    path: /bien
    controller: App\Controller\BienController::index

wish:
    path: wish/{id}
    controller: App\Controller\HomeController::addAction

remove:
    path: remove/{id}
    controller: App\Controller\HomeController::remove


categorie:
    path: categorie/{id}
    controller: App\HomeController::categorie

ContactMessage: 
    path: message
    controller: App\Controller\ContactController::message

contact:
    path: contact
    controller: App\Controller\ContactController::index