index:
    path: /
    controller: App\Controller\HomeController::index
bien:
    path: /bien
    controller: App\Controller\BienController::index

wish:
    path: wish/{id}
    controller: App\Controller\HomeController::addAction

categorie:
    path: categorie/{id}
    controller: App\HomeController::categorie    

contact:
    path: contact
    controller: ContactController::index